application:
  actions: actions
  runtimeManifest:
    packages:
      wknd-chatgpt:
        license: Apache-2.0
        actions:
          chat:
            function: actions/chatgpt/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              CHATGPT_SECRET_KEY: $CHATGPT_SECRET_KEY
            annotations:
              require-adobe-auth: false    
      web-services-dev:
        license: Apache-2.0
        actions:
          file-name-to-metadata:
            function: actions/dev/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              AEM_URL: $DEV_AEM_URL
              AEM_CREDENTIAL: $DEV_AEM_CREDENTIAL
              AEM_ASSET_API_FIXED_PATH: $DEV_AEM_ASSET_API_FIXED_PATH
              AEM_QUERY_BUILDER_API_FIXED_PATH: $DEV_QUERY_BUILDER_API_FIXED_PATH
            annotations:
              require-adobe-auth: false
          metadata-mapping:
            function: actions/dev/metadata-mapping.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              AEM_CREDENTIAL: $DEV_AEM_CREDENTIAL
              AEM_ASSET_API_FIXED_PATH: $DEV_AEM_ASSET_API_FIXED_PATH
              AEM_QUERY_BUILDER_API_FIXED_PATH: $DEV_QUERY_BUILDER_API_FIXED_PATH
              META_DATA_MAP_SOURCE: $DEV_META_DATA_MAP_SOURCE
            annotations:
              require-adobe-auth: false
      web-services-dell:
        license: Apache-2.0
        actions:
          file-name-to-metadata:
            function: actions/dell/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              AEM_URL: $DELL_AEM_URL
              AEM_CREDENTIAL: $DELL_AEM_CREDENTIAL
              AEM_ASSET_API_FIXED_PATH: $DELL_AEM_ASSET_API_FIXED_PATH
              AEM_QUERY_BUILDER_API_FIXED_PATH: $DELL_QUERY_BUILDER_API_FIXED_PATH
            annotations:
              require-adobe-auth: false
